Sapd/HeadsetControl

- main.c
Tested this with various different volume levels on Ubuntu 17.10 with Logitech G533.  Seems to work great.
> Adding G533 Support

- src/device_registry.c
- src/devices/CMakeLists.txt
- src/devices/corsair_voidpro.c
- src/devices/corsair_voidpro.h
- src/utility.h
- udev/corsairvoidpro.rules
> Void 0x0a14

- src/devices/corsair_voidpro.c
> Fixes issue #13

- cmake_modules/Findhidapi.cmake
> Changed CMake to prefer hidapi-hidraw over hidapi-libusb.

- README.md
These dependencies seemed to be what I needed to get things going on my Antergos (arch-based) system.
> Arch Linux dependencies.

- src/devices/logitech_g533.c
> Implement battery status for G533

- README.md
Update description for udev-setup slightly, I had a hard time figuring out that "systemctl restart udev" does not suffice.
> Update udev instructions

- README.md
> Adding ebuild information to README

- README.md
The tool is not only about sidetone any more, so add a more general introduction
> Adjust introductory section and add invactive time

- README.md
- src/device_registry.c
- src/devices/CMakeLists.txt
- src/devices/logitech_gpro.c
- src/devices/logitech_gpro.h
- udev/70-headsets.rules
Sidetone is working fine for me. The headset does not support any of the other features.
The Logitech G PRO X is very similar to the G PRO and I included its product id as a comment. But since I can't test it, I don't want to include it. If someone gets his hands on the device it might be very simple to add it as well.
> Add support for Logitech G PRO

- src/devices/corsair_void.c
I had made a Typo in the other pull request and didn't knew how to change it so I made another
> Fix for Corsair Void Pro wireless low battery error

- README.md
Hi, I'm working on a System Tray Indicator/GUI for windows, I'm still in its first commits, but I plan on adding more features, to make it more functional as [centic9/headset-charge-indicator](https://github.com/centic9/headset-charge-indicator/).
> Added Windows GUI option for HeadsetControl

- src/devices/logitech_gpro.c
Add alternative Headset ID for Logitech G PRO X
> Add alternative Headset ID

- README.md
Add SteelSeries Arctis 1, Logitech G635 and G733 and a few more Corsair Void models
> Update list of supported headsets

- README.md
- src/device_registry.c
- src/devices/CMakeLists.txt
- src/devices/logitech_g432.c
- src/devices/logitech_g432.h
- udev/70-headsets.rules
Support for Logitech G432 (Sidetone). I pretty much copied the template from the Logitech G Pro. Only tested on Linux so far.
Implements #120
> Added support for logitech G432 (#120)

- README.md
- src/device_registry.c
- src/devices/CMakeLists.txt
- src/devices/steelseries_arctis_pro_wireless.c
- src/devices/steelseries_arctis_pro_wireless.h
Supports headset battery status, setting timeout, and setting
sidetone values.
Closes #151
> Add support for SteelSeries Arctis Pro Wireless

- README.md
- src/main.c
Updated README.md and the -h help menu to be more verbose about the -m option.
> Be more verbose about the -m option

- .clang-format
- src/CMakeLists.txt
- src/dev.c
- src/device.c
- src/device.h
- src/devices/corsair_void.c
- src/devices/logitech_g430.c
- src/devices/logitech_g432.c
- src/devices/logitech_g533.c
- src/devices/logitech_g633_g933_935.c
- src/devices/logitech_g930.c
- src/devices/logitech_gpro.c
- src/devices/logitech_zone_wired.c
- src/devices/roccat_elo_7_1_air.c
- src/devices/roccat_elo_7_1_usb.c
- src/devices/steelseries_arctis_1.c
- src/devices/steelseries_arctis_7.c
- src/devices/steelseries_arctis_9.c
- src/devices/steelseries_arctis_pro_wireless.c
- src/hid_utility.c
- src/main.c
> Support different Interface/Usage/UsagePage-IDs per headset

- README.md
- src/device.h
- src/devices/corsair_void.c
- src/devices/logitech_g533.c
- src/devices/logitech_g633_g933_935.c
- src/devices/roccat_elo_7_1_air.c
- src/devices/roccat_elo_7_1_usb.c
- src/devices/steelseries_arctis_1.c
- src/devices/steelseries_arctis_7.c
- src/devices/steelseries_arctis_9.c
- src/devices/steelseries_arctis_pro_wireless.c
- src/main.c
Also:
- Improve parameters with numbers, check if they are really numbers
- Pass error codes to program return
- On timeout, program returns -101
Fixed #193
> Added timeout parameter for reading, default is 5s

- src/device.c
- src/device.h
- src/devices/steelseries_arctis_7_plus.c
- src/main.c
As mentioned in PR #209 I've added the support for equalizer presets. 
Not sure if this is the way you wan't to handle this. If something is off please propose the changes.
> feat: support equalizer presets for arctis 7+

- src/devices/steelseries_arctis_1.c
Added the ID for Arctis 7X to the Arctis 1 class.
> Add Arctis 7X support

- src/utility.c
- src/utility.h
This implementation helps me out to see faster changes in responses,  I've used it for debugging battery status in nova 7.
> hexdump method to speed runtime protocol debugging

- src/devices/steelseries_arctis_7_plus.c
Add chatmix support for 7+ based on arctis nova implementation which turned out to work well.
> feat: add arctis 7+ chatmix

- README.md
Added the supported features for the G Pro to the README.md.
> Updated README.md to match supported G Pro features.

- README.md
Added instructions to install on NixOS.
> Add NixOS install instructions

- README.md
Added third party software to README.md.
> Added third party software to README.md

- README.md
Added link to HeadsetControl-Qt repo in readme.
> Added HeadsetControl-Qt third party project to readme

- README.md
Updated third party software that was on a fork and now is in original repo.
> Updated third party software

- README.md
- src/devices/steelseries_arctis_1.c
Added Steelseries Arctis 7P to 1/7X
> Add device Steelseries Arctis 7P

- .github/workflows/build-windows.yml
Updated GitHub Actions to use upload-artifact@v4
Tested there https://github.com/nicola02nb/HeadsetControl/actions/runs/13114359528/job/36584992863
> Update GitHub Actions to use upload-artifact@v4

- CMakeLists.txt
- src/dev.c
- src/device.h
- src/devices/corsair_void.c
- src/devices/headsetcontrol_test.c
- src/devices/hyperx_calphaw.c
- src/devices/steelseries_arctis_nova_5.c
- src/main.c
- src/output.c
- src/utility.h
> Fix various spelling issues

- .github/workflows/continuos-release.yml
- src/main.c
Continuous build for linux didn't have linked libraries
> Fix for linux continuous release
