Sapd/HeadsetControl

README.md, src/device.h, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis7.c, src/devices/steelseries_arctis7.h, src/main.c, src/utility.h, udev/steelseriesarctis7.rules
This currently only supports setting (or disabling) the sidetone feature.
Sadly, this control station falls out of line by using Output Requests instead of Feature Requests, so the code is a tad different from all the other implementations.
Further, the request needs to be sent to a non-default interface, which touches on #8. Thus, I've implemented initial interface opening, which SHOULD be backwards compatible due to initializing the device structure statically (and thus nulling the memory block) and assuming that `hid_enumerate` returns the default interface as the first one - which would be what `hid_open(vid, pid)` would normally open.
I was not able to actually test this, though, so please go ahead and make sure it doesn't break your devices.
=> Add support for SteelSeries Arctis 7.

src/main.c
For usage in scripts I do not want to parse the output and filter out
the usefull infomration or clutter the line with redirects to /dev/null.
Therefore I added a option, that removes every output, except whith the
-b-switch, where the battery-percentage (or -1 for loading) are printed.
While doing so, the default changed a bit:
Only when the -h-swich is present, we output name and author of this
programm.
Further: my Texteditor removed some whitespaces in empty lines....
=> Added a switch for short output: -c

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctispro_2019.c, src/devices/steelseries_arctispro_2019.h, udev/50-steelseries-arctis-pro-2019.rules
This adds support for the Steel Series Arctis Pro 2019 edition (The wired usb one without a dac). Tested on Manjaro.
=> Add support for the Seel Series Arctis Pro 2019 edition

udev/50-corsair-void-elite.rules, udev/50-corsair-void-pro-usb.rules, udev/50-corsair-void-pro.rules, udev/50-corsair-void.rules, udev/50-corsair_void_rgb_usb.rules, udev/50-logitech-g430.rules, udev/50-logitech-g533.rules, udev/50-logitech-g633.rules, udev/50-logitech-g930.rules, udev/50-logitech-g933.rules, udev/50-logitech-g935.rules, udev/50-steelseries-arctis-7-2019.rules, udev/50-steelseries-arctis-7.rules, udev/50-steelseries-arctis-pro-2019.rules, udev/70-headsets.rules
The `uaccess` udev TAG allows to dynamically set permission to
physically connected users thus we can avoid giving RAW access to the
devices to everyone.
Note: I also merged the rules into a single file for simplicity and moved it from `50-*` to `70-*` because it is the norm used in multiple projects settings hidraw permissions.
=> udev: give rights only to seated user

README.md, src/devices/logitech_g930.c
I simply ported (copied actually) it from https://github.com/Roliga/g930-battery-percentage
Seems to work quite good. 
Issues:
- Charging status is not read from the device
- Runtime / Charge time is not read
- During Charge, battery goes over 100%
I believe the code directly reads the voltage, maybe someone can improve that in a later step.
This is my first pullrequest, is everything in order?
=> Add battery status for G930

udev/70-headsets.rules
Should probably be "GOTO" here.
=> Fix invalid GOGO in udev rules

.gitignore, src/device.h, src/devices/steelseries_arctis.c, src/main.c
Add a new capability CAP_INACTIVE_TIME to set time until a device turns itself off. 
Implement this for SteelSeries Arctis which supports this.
=> Add capabilitiy for setting inactive time

src/devices/logitech_g633_g933_935.c
Just added the appropriate device ID (`0x0a89`) to the file already implementing g633 support.
=> Added support for the g635

README.md, src/device.h, src/devices/steelseries_arctis.c, src/main.c
This is a feature of the SteelSeries Arctis headset when using the bundled Windows software which allows to adjust how Game-Sound is mixed with live audio-chat via a slider on the Headset.
Reading this value allows arbitrary integrations to be built, i.e. you could use this to control play-speed in your audio player or any other integration that can be done via reading the setting of a hardware slider.
Changes:
* Added a new capability "CAP_CHATMIX_STATUS"
* Added option "-m" to read it
* Implemented the capability for the Steelseries Arctis
* Additionally fixed a few typos in the README
=> Add capability to read the value of the "chat-mix" slider on SteelSeries Arctis

README.md, src/devices/steelseries_arctis.c
The SteelSeries Arctis 7 does not have LEDs as part of the headset, but there is a LED on the base-station which usually blinks when the headset is not reachable. 
When you turn off the Headset on purpose, this blinking might be irritating, so there is a protocol to turn off that LED.
This PR uses the existing "switch LED" commandline option to enable/disable this LED.
=> SteelSeries Arctis: Use LED-capability for the LED on the base-station

src/devices/corsair_void.c
Since all of the controls seem to work (but no lights, since there are none) I didn't want to create a new file. Even though this model isn't from the "Void" range.
Edit: Thanks for this work btw, I'm so happy I finally have a nice Linux tool.
=> Add support for Corsair HS70 Pro.

src/device_registry.c, src/devices/CMakeLists.txt, src/devices/corsair_void.c, src/devices/logitech_g633_g933_935.c, src/devices/steelseries_arctis.h, src/devices/steelseries_arctis_1.c, src/devices/steelseries_arctis_1.h, src/devices/steelseries_arctis_7.c, src/devices/steelseries_arctis_7.h, src/main.c, udev/70-headsets.rules
Partially working Arctis 1 support
Battery level doesn't work. Not sure why yet. But atleast I can set sidetalking from linux now.
Forked steelseries_arctis.c into two, since the arctis 1 seems a bit too different.
=> Arctis 1 support

udev/70-headsets.rules
Added an additional udev rule for Corsair Pro wireless headsets. This will close issue "#96 opened on Jun 6 by simonoesterle".
=> adding udev rule for Corsair Pro wireless headset

src/device.h, src/devices/corsair_void.c, src/main.c
Relevant issue is #102.
This PR adds an additional flag to the `battery_status` enum and detects if the battery belongs to a disconnected device, making the returned battery status value useless. This has been implemented and tested for the Corsair VOID PRO Wireless headset and should be valid for any other Corsair device supported by HeadsetControl.
As I do not have any access to other devices supported by HeadsetControl, I'm unable to implement something similar for them. As it is, this PR should not negatively impact any of said other devices, but improve the output for Corsair headsets.
=> Implements detection of battery not being available on VOID PRO Wireless

src/devices/corsair_void.c, udev/70-headsets.rules
Hi, in this PR I'm adding support to [Corsair HS70](https://www.corsair.com/us/en/Categories/Products/Gaming-Headsets/Wireless-Headsets/HS70-Wireless-Gaming-Headset/p/CA-9011179-NA) and improving the support to [HS70 PRO](https://www.corsair.com/us/en/Categories/Products/Gaming-Headsets/Wireless-Headsets/HS70-PRO-WIRELESS-Gaming-Headset/p/CA-9011211-NA). 
Basically, I insert a new device ID in `src/devices/corsair_void.c` (HS70) and updated the `udev/70-headsets.rules` with the HS70 and HS70 Pro data, thus allowing the `headsetcontrol` command works without `sudo` to its devices =)
=> Adding Corsair HS70 support

src/device.h, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_1.c, src/devices/steelseries_arctis_1_xbox.c, src/devices/steelseries_arctis_1_xbox.h
Battery level _seems_ to be correct. I couldn't/didn't test the sidetone level (I have no idea what that is), and the timeout didn't work either, but I wonder how it detects usage (I had the mic disabled on the headset, but PulseAudio running).
=> Add support for the SteelSeries Arctis 1 Wireless for XBox

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_9.c, src/devices/steelseries_arctis_9.h, udev/70-headsets.rules
I added support for the new SteelSeries Arctis 9.
I'm not entirely sure what method they are using to report the battery level. So I'm just using the [reported values](https://github.com/rhwilrForks/HeadsetControl/blob/master/src/devices/steelseries_arctis_9.c#L15-L16) and mapping it to a percentage. Also, the sidetone setting is some exponential curve, so a did my best to map it to a scale that feels linear.
Hope you find this useful, as others seem to be looking for this as well (#115).
If you require any changes, feel free to let me know.
=> Added support for SteelSeries Arctis 9

README.md
My overlay (where the ebuild from wiki was duplicated) has been added to the list of Gentoo overlays, so a user can now just enable it and install the package.
=> Added overlay instructions for Gentoo ebuild

src/device_registry.c, src/devices/CMakeLists.txt, src/devices/logitech_zone_wired.c, src/devices/logitech_zone_wired.h, udev/70-headsets.rules
This PR adds support for the Logitech Zone Wired headset and configuring its sidetone volume.
=> Add sidetone support for Logitech Zone Wired headset

README.md, src/device.h, src/devices/logitech_zone_wired.c, src/main.c
Add support for the following two capabilities:
- `-v 0|1`: Enables or disables "voice prompts" (i.e. accoustic announcements like "mute on")
- `-r 0|1` Enables or disables "rotate to mute" (auto-mute the microphone when it's rotated upwards away from the mouth into a vertical position)
I've implemented both features for the Logitech Zone Wired (#140). I intentionally put this feature set into a different PR, as this is a global change, rather than simply a new device.
=> Add two additional capabilities

README.md, src/main.c
When invoking headsetcontrol in other tools it would be useful to be able to dynamically adjust to the capabilities of the currently detected headset.
Therefore this PR adds a commandline option "-?" which prints out a list of things that will work for the current headset
```
$./headsetcontrol -?
Found SteelSeries Arctis (7/Pro)!
Supported capabilities:
* set sidetone
* read battery level
* switch lights
* set inactive time
* read chat-mix
```
Short output is also supported to make it easy to use this in other tools:
```
$./headsetcontrol -? -c
sblim
```
=> Allow to query for capabilities of current headset

README.md
Fedora commands now available in the README file.
=> Improve README: Add Fedora commands

CMakeLists.txt
I'm maintaining HeadsetControl package for the distribution I use (ALT Sisyphus). While working on update to 2.5, I found that a couple of minor changes to `CMakeLists.txt` would make my job as a maintainer easier.
First, as most of (binary) distros do, we are building our package in a controlled environment that does not have a C++ compiler by default. Specifying that HeadsetControl is C-only project avoids the necessity to install it there.
Second, we're installing udev rules to `/lib/udev/rules.d`, which is not a symlink to  `/usr/lib/udev/rules.d` or anything like that. So I added an option to specify where CMake should put the udev rules file.
=> cmake improvements for distros

src/devices/steelseries_arctis_1.c
Not sure if the addresses are different for the Xbox variant, but my Arctis 1 Wireless (firmware 1.6.0.0) uses 0x53 instead of 0x51 for setting the inactivity shutdown timer. 
Also added the correct usage page/ID for Windows support and it's completely functional on Windows now
=> Arctis 1 Wireless - fixed inactive time functionality and added Windows Support

src/devices/logitech_g533.c
Windows Support for Logitech G533 has been added and tested. These capabilities are supported:
- sidetone
- battery status
Have a nice day!
=> Added windows support for Logitech G533

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_7_plus.c, src/devices/steelseries_arctis_7_plus.h
This adds Steelseries Arctis 7 Plus support for side tone and inactive time (tested). 
~I couldn't find in wireshark any info regarding battery status so this is skipped for now. I would welcome help though in this matter.~
Additionally this model support a few Equalizer presets (also custom settings) that I can successfully change via following commands:
```sh
./headsetcontrol --dev -- --device 0x1038:0x220e --interface 3 --send "0x0, 0x33, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 00"
./headsetcontrol --dev -- --device 0x1038:0x220e --interface 3 --send "0x0, 0x33, 0x1f, 0x20, 0x1a, 0x15, 0x15, 0x16, 0x16, 0x16, 0x16, 0x23, 00"
./headsetcontrol --dev -- --device 0x1038:0x220e --interface 3 --send "0x0, 0x33, 0x1e, 0x1b, 0x15, 0x10, 0x10, 0x13, 0x1b, 0x1e, 0x20, 0x1f, …
```
=> feat: add steelseries arctis 7 plus (2021) support

README.md
Adds missing information about equalizer presets into the README.
=> docs: add equalizer presets info to readme

CMakeLists.txt
FreeBSD dont uses udev.
Fixes #222
Thank you!
=> Also dont install udev files on FreeBSD

src/devices/logitech_gpro.c, src/utility.c, src/utility.h
I have moved the calculation of the battery level over to `utility.c` and updated the code for the Logitech Pro X to use it. I did not touch the `logitech_g633_g933_935.c` as I cannot verify the correctness, when porting it.
=> Moving battery calculation for lipo discharge into utility.c

src/devices/steelseries_arctis_7_plus.c
Adds a new device id for the Arctis 7P+ Playstation 5 edition.
Bus 001 Device 013: ID 1038:2212 SteelSeries ApS Arctis 7P+
$ headsetcontrol -?
Found SteelSeries Arctis 7+!
Supported capabilities:
* sidetone
* battery status
* inactive time
* equalizer preset
=> Adding support for Arctis 7p+ Playstation

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/logitech_g535.c, src/devices/logitech_g535.h
Added support for setting the sidetone level for the Logitech G535 headset. Not sure how to add support for querying the battery level, though
=> Initial support for Logitech G535

src/devices/logitech_g533.c
This adds inactive timeout for g533, based on the g933-utils repository.
I've left the comments about the repository source, as this also draws upon that for the specification.
=> Add inactive_timeout for g533

src/main.c
Repeat the commands requested after sleeping 2 seconds. This can be
useful to monitor a battery status.
=> Add a monitor mode

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_nova_7.c, src/devices/steelseries_arctis_nova_7.h
Adds support for the new SteelSeries Arctis Nova 7 and Arctis Nova 7x Headset
=> adds support for SteelSeries Arctis Nova 7

src/devices/steelseries_arctis_nova_7.c
fixed sidetone, equalizer and add information how to support all headphone features.
=> fix steelseries arctis nova 7 support

README.md, src/dev.c, src/device.c, src/device.h, src/devices/steelseries_arctis_7_plus.c, src/devices/steelseries_arctis_nova_7.c, src/main.c, src/utility.c, src/utility.h
Add custom equalizer bands values support and implement it for arctis 7+ and nova 7.
Resolves #253
=> feat: add custom equalizer to arctis 7+ and nova 7

src/devices/steelseries_arctis_9.c
System Information: 
```
rscott@home ~ $ udevadm info --query=all /sys/devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5.2/
P: /devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5.2
M: 3-5.2
R: 2
U: usb
T: usb_device
D: c 189:272
N: bus/usb/003/017
L: 0
V: usb
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5.2
E: SUBSYSTEM=usb
E: DEVNAME=/dev/bus/usb/003/017
E: DEVTYPE=usb_device
E: DRIVER=usb
E: PRODUCT=1038/12c2/74
E: TYPE=0/0/0
E: BUSNUM=003
E: DEVNUM=017
E: MAJOR=189
E: MINOR=272
E: USEC_INITIALIZED=10274180
E: ID_VENDOR=SteelSeries
E: ID_VENDOR_ENC=SteelSeries
E: ID_VENDOR_ID=1038
E: ID_MODEL=SteelSeries_Arctis_9
E: ID_MODEL_ENC=SteelSeries\x20Arctis\x209
E: ID_MODEL_ID=12c2
E: ID_REVISION=0074
E: ID_SERIAL=SteelSeries_SteelSeries_Arctis_9
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: …
```
=> s9 only supports a single report, first byte must be set to 0x0

src/devices/steelseries_arctis_9.c
#260 
inputs does not work, seems input is on separate report IDs, works now.
hid_write sometimes hangs, unsure why.
=> oversight: whilst output is on a single report (0x0), input is on separate reports.

src/devices/steelseries_arctis_7_plus.c
Adds support for the XBox version of the Arctis 7+ using a different device id(ID 1038:2216 SteelSeries ApS Arctis 7X+)
=> Add Support for Arctis 7X+ (Xbox)

src/devices/corsair_void.c
Not sure why, but there seems to be another product ID for these headphones. Mine are white so it could be the black/yellow/white combo we have here.
=> Add Corsair VOID RGB USB 3

README.md, src/devices/logitech_g535.c, src/utility.c, src/utility.h
Building upon #234, this will improve the Logitech G535 support by adding battery status and inactive time.
=> Improve Logitech G535 support

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/hyperx_calphaw.c, src/devices/hyperx_calphaw.h, src/devices/hyperx_cflight.c, src/devices/logitech_g430.c, src/devices/logitech_g633_g933_935.c, src/devices/roccat_elo_7_1_air.c
HyperX Cloud Alpha Wireless
Supported capabilities:
* sidetone
* battery status
* inactive time
* voice prompts
Based on lehnification/hyperx-cloud-alpha-wireless-tray for most payloads
=> Add HyperX Cloud Alpha Wireless Support

src/devices/corsair_void.c, src/hid_utility.c
Fixes https://github.com/Sapd/HeadsetControl/issues/281
=> Mac ignore interfaceid

src/devices/logitech_g633_g933_935.c
New Logitech G733 has diferent DEVICE ID
Example: ID 046d:0afe Logitech, Inc. G733 Gaming Headset
Added ID and name
=> Add new ID Logitech G733

src/utility.c, src/utility.h
=> Fix spline function

src/devices/steelseries_arctis_7.c
SteelSeries Arctis Pro with GameDAC has a different device ID than with no GameDAC.
Resolves #167.
=> Adds Device ID for SteelSeries Arctis Pro GameDAC

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_nova_pro_wireless.c, src/devices/steelseries_arctis_nova_pro_wireless.h
Added some support for Steelseries Arctis Nova Pro Wireless.
Equalizers and light (mic mute led) should be possible to control as well, will try to add that in the coming days. But if life gets in the way this might be enough for a start.
=> Add Steelseries Arctis Nova Pro Wireless support

src/devices/steelseries_arctis_nova_7.c
It's the same headset as basic Nova 7, but it's has different name and id, so I just added it to the list. Tested with my own pair on linux.
=> Add support for  Steelseries Arctis Nova 7 Diablo IV edition

src/device.c, src/device.h, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_nova_3.c, src/devices/steelseries_arctis_nova_3.h, src/main.c
Hello! This PR adds support for the Arctis Nova 3 headset. Alongside this, it adds 2 new capabilities that this headset implements, those being the following:
- ``CAP_MICROPHONE_MUTE_LED_BRIGHTNESS``
- ``CAP_MICROPHONE_VOLUME``
The headset also implements the following existing capabilities:
- ``CAP_SIDETONE``
- ``CAP_EQUALIZER_PRESET``
- ``CAP_EQUALIZER``
Closes #294.
=> Add Arctis Nova 3 support

README.md, src/dev.c, src/device.h, src/devices/steelseries_arctis_7_plus.c, src/devices/steelseries_arctis_nova_3.c, src/devices/steelseries_arctis_nova_7.c, src/devices/steelseries_arctis_nova_pro_wireless.c, src/main.c, src/utility.c, src/utility.h
Hello! This PR introduces an internal equalizer baseline and band limit. On the one hand, having the baseline means is that, instead of having to input band values specific to the device for the equalizer, e.g.:
``headsetcontrol -e "0x1c 0x19 0x11 0x14 0x14 0x14"``
you can specify the band value shown in the software, e.g.:
``headsetcontrol -e "4 2.5 -1.5 0 0 0"``
Essentially, the baseline is the band value sent in a USB command when it's flat. The band limit, on the other hand, sets limits for those arbitrary values in the equalizer argument string. For example, on the Arctis Nova 3, the minimum and maximum band values are ``-6`` and ``+6`` respectively.
Moreover, this PR fixes potential bugs. For example, the send and send-feature commands used a **signed** byte buffer instead of an …
=> Introduce internal equalizer baseline and band limit

src/main.c
This closes issue #322. It adds the command line flag `--connected` alias `-t` (standing for test)
to check if there is a headset connected.
It works by first checking if a headset is detected. 
If it does, there are 2 cases:
- a headset is connected and turned on
- a wireless headset's usb is connected but it is turned off
These 2 cases are differentiated by first checking if the
model has the battery status capability.
If it doesn't, it is wired connected.
If it does, the battery status is checked. If an error is returned, the headset
is turned off.
For example, this option can be integrated in bash scripts using
`if headsetcontrol -t ; then ; <do something> ; fi`
=> Closes issue #322 | Add option to check if headset is connected

CMakeLists.txt, src/main.c, src/output.c, src/utility.c, src/utility.h
fixes #335
It would probably be best to actually check the return values for errors on writing. Maybe somethign along these lines:
```c
#define ASSERT_ASPRINTF(x) { if (x < 0) {fprintf(stderr, "Error formatting output"); }
```
=> Rename asprintf to _asprintf to avoid unused-result warnings

src/devices/steelseries_arctis_nova_7.c
The ID for Arctis Nova 7X seems to be incorrect.
```
❯ headsetcontrol -b
No supported device found
❯ headsetcontrol --dev -- --list --device 0x1038:0x2258
Device Found
VendorID: 0x1038
ProductID: 0x2258
path: /dev/hidraw7
serial_number: 
Manufacturer: SteelSeries
Product:      Arctis Nova 7X
Interface:    3
Usage-Page: 0xffc0 Usageid: 0x1
Device Found
VendorID: 0x1038
ProductID: 0x2258
path: /dev/hidraw8
serial_number: 
Manufacturer: SteelSeries
Product:      Arctis Nova 7X
Interface:    4
Usage-Page: 0xc Usageid: 0x1
Device Found
VendorID: 0x1038
ProductID: 0x2258
path: /dev/hidraw9
serial_number: 
Manufacturer: SteelSeries
Product:      Arctis Nova 7X
Interface:    5
Usage-Page: 0xff00 Usageid: 0x1
```
After changing the ID and recompiling and installing:
```
❯ headsetcontrol -b
Found …
```
=> Fix: Add ID for Arctis Nova 7X revision

README.md, src/device_registry.c, src/devices/CMakeLists.txt, src/devices/steelseries_arctis_nova_5.c, src/devices/steelseries_arctis_nova_5.h, src/main.c
Add support for SteelSeries Arctis Nova 5.
The commands are very similar to SteelSereis Arctis Nova Pro Wireless.
Except some differences:
* microphone mute led values have other values for medium and high
* number of side tone steps
* number of mic volume steps
I didn't trust the set_equalizer and set_equalizer_preset command from Arctis Nova Pro Wireless that much.
Therefore I've left out the respective capabilities.
There are many presets one can select in the SteelSeries GG App, those are just set as equalizer band settings.
The set_equalizer command sent by SteelSeries GG uses the same ID as for Arctis Nova Pro Wireless for the equalizer setting, but the format looks different. 
The equalizer bands are transferred differently it seems.
Each band value consist of 6 bytes
- 2 byte …
=> Feat: Add support for SteelSeries Arctis Nova 5

README.md, src/devices/steelseries_arctis_nova_5.c
Added respective capability and implement setting the well known SteelSeries EQ presets and EQ Settings
I figured out the format by toying around with a self made capture cotaining all the profiles supported by SteelSeries GG  and trying decoding them and comparing with the values provided by the UI: https://gitlab.com/hrzlgnm/steelseries-gg-profiles
=> Add Arctis Nova 5 EQ Presets and Equalizer settings support

README.md, src/devices/steelseries_arctis_nova_5.c
Added the product id of the SteelSeries Arctis Nova 5X to the SteelSeries Arctis Nova 5 family.
Added ChatMix capability for Nova 5 / 5X. (Works on 5X, cannot confirm 5)
The 5X adds a switch on the base station to allow it to work with Xbox. When the switch is set to `USB`, it seems to be the exact same as the normal Nova 5.
=> Added Nova 5X as a SteelSeries Arctis Nova 5

src/devices/steelseries_arctis_nova_7.c
Rolled back code for artics nova 7 battery level (it was more accurate).
=> Rolled back code for artics nova 7 battery (it was more accurate)

src/dev.c, src/devices/steelseries_arctis_nova_7.c
Added --repeat option for --dev arguments.
Example of usage:
`headsetcontrol --dev -- --device 0x1038:0x2202  --interface 3 --send 0x00,0xb0 --receive --repeat 5`
It essentially repeats command evey 5 seconds (sleep between one to another can be changed and should be > 1)
It will be useful to users that are not familiar with wireshark or other programs to track changing bytes for features like battery, chatmix, etc..
=> Added --repeat option for --dev arguments

src/devices/logitech_g633_g933_935.c
I just picked up a G733 and I couldn't originally manage it with HeadsetControl. I found out it actually has a different hardware ID than other versions of the G733 did! So I added it to ID array, and it works now.
=> Add new G733 hardware ID

src/devices/steelseries_arctis_nova_pro_wireless.c
Added missing devide ProductID.
Related to #375
=> Artics nova basestation

.github/workflows/continuos-release.yml
Created a CI workflow files that compiles and publish a "Continuos build" on every push to `master` branch.
This gives users a way to get the latest features without building the project on their own
You can check the result on [my fork](https://github.com/nicola02nb/HeadsetControl)
=> Add CI workflow to publish a continuous release

.github/workflows/continuos-release.yml
Atm the `windows.zip` file of the `continuous` build contains a file without `.exe` extension.
That fixes the CI
=> Fix build workflow: update zip command to include all matching artifacts

README.md
Updated `README.md` to include prerequisites for building on openSUSE.
=> Add openSUSE prerequisites

src/main.c
Fix for #396 
Renamed `selected_device` for consistency, fixed bug when `-d` arg is not specified
=> Multiple device fix

README.md, src/devices/audeze_maxwell.c, src/main.c
- Added a delay to prevent issues with rapid consecutive requests, matching the timing used by Audeze HQ.
- Improved the way all info requests are made
- Added microphone status detection.
- Added all initialization requests used by Audeze HQ to prevent problems.
- Added chatmix capability
- Added voice prompt capability
- Fixed `-o` command querying each info capability twice
Related to #410
=> Fix rapid battery request issue on Audeze Maxwell
